INSERT INTO job_applied 
    (job_id, 
    application_sent_date, 
    custom_resume,
     resume_file_name, 
     cover_letter_sent, 
     cover_letter_file_name, 
     status) 
VALUES
        (1,
        '2023-04-01', 
        TRUE,
        'resume1.pdf',
        TRUE, 
        'cover_letter1.pdf',
         'submitted'),
        (2,
        '2023-04-03',      
        FALSE,
        'resume2.pdf',
        FALSE,
        NULL,
        'submitted'),
        (3,
        '2023-04-05',
        TRUE,
        'resume3.pdf',
        TRUE,
        'cover_letter3.pdf',
        'submitted'), 
        (4,
        '2023-04-07',
        FALSE,
        'resume4.pdf',
        FALSE,
        NULL,
        'in review'),
        (5,
        '2023-04-10',
        TRUE,
        'resume5.pdf',
        TRUE,
        'cover_letter5.pdf',
        'rejected');

        SELECT * FROM job_applied;